const BasketballConfig = {
  desktop: [{
    left: true,
    backgroundColor: '#FFFFFF',
    textColor: '#000000',
    order: '01',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'CONNECTION',
    info: 'Connect with talented athlete directly, you can watch their skills through video showreels directly from Surface 1.',
    height: '256px',
    letterSpace: '0',
    maxWidth: '571px',
  }, {
    left: true,
    backgroundColor: '#F5F4F9',
    textColor: '#000000',
    order: '02',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'COLLABORATION',
    info: 'Work with recruiter to increase your chances of finding talented athlete.',
    height: '245px',
    letterSpace: '0.65px',
    maxWidth: '717px',
  }, {
    left: true,
    backgroundColor: '#090C35',
    textColor: '#FFFFFF',
    order: '03',
    bulletColor: '#8F6BE8',
    bulletLineColor: '#FFFFFF',
    title: 'GROWTH',
    info: 'Save your time, recruit proper athlets for your team.',
    height: '268px',
    letterSpace: '0.65px',
    maxWidth: '717px',
  }],
  tablet: [{
    left: true,
    backgroundColor: '#FFFFFF',
    textColor: '#000000',
    order: '01',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'CONNECTION',
    info: 'Connect with talented athlete directly, you can watch their skills through video showreels directly from Surface 1.',
    height: '191px',
    letterSpace: '0',
    maxWidth: '432px',
  }, {
    left: true,
    backgroundColor: '#F5F4F9',
    textColor: '#000000',
    order: '02',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'COLLABORATION',
    info: 'Work with recruiter to increase your chances of finding talented athlete.',
    height: '235px',
    letterSpace: '0.93px',
    maxWidth: '432px',
  }, {
    left: true,
    backgroundColor: '#090C35',
    textColor: '#FFFFFF',
    order: '03',
    bulletColor: '#8F6BE8',
    bulletLineColor: '#FFFFFF',
    title: 'GROWTH',
    info: 'Save your time, recruit proper athlets for your team.',
    height: '207px',
    letterSpace: '0.93px',
    maxWidth: '455px',
  }],
  mobile: [{
    left: true,
    backgroundColor: '#FFFFFF',
    textColor: '#000000',
    order: '01',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'CONNECTION',
    info: 'Connect with talented athlete directly, you can watch their skills through video showreels directly from Surface 1.',
    height: '238px',
    letterSpace: '0',
    maxWidth: '283px',
  }, {
    left: true,
    backgroundColor: '#F5F4F9',
    textColor: '#000000',
    order: '02',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'COLLABORATION',
    info: 'Work with recruiter to increase your chances of finding talented athlete.',
    height: '238px',
    letterSpace: '0.93px',
    maxWidth: '283px',
  }, {
    left: true,
    backgroundColor: '#090C35',
    textColor: '#FFFFFF',
    order: '03',
    bulletColor: '#8F6BE8',
    bulletLineColor: '#FFFFFF',
    title: 'GROWTH',
    info: 'Save your time, recruit proper athlets for your team.',
    height: '238px',
    letterSpace: '0.93px',
    maxWidth: '283px',
  }],
}
export default BasketballConfig