const FootballConfig = {
  desktop: [{
    left: false,
    backgroundColor: '#FFFFFF',
    textColor: '#000000',
    order: '01',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'CONNECTION',
    info: 'Connect with coaches directly, you can ping coaches to view profile.',
    height: '216px',
    letterSpace: '0',
    maxWidth: '601px',
  }, {
    left: false,
    backgroundColor: '#F5F4F9',
    textColor: '#000000',
    order: '02',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'COLLABORATION',
    info: 'Work with other student athletes to increase visability. When you share and like other players videos it will increase your visability as a player. This is the team work aspect to Surface 1.',
    height: '256px',
    letterSpace: '0.93px',
    maxWidth: '717px',
  }, {
    left: false,
    backgroundColor: '#5E3DB3',
    textColor: '#FFFFFF',
    order: '03',
    bulletColor: '#000000',
    bulletLineColor: '#FFFFFF',
    title: 'GROWTH',
    info: 'Resources and tools for you to get better as a student Athelte. Access to training classes, tutor sessions, etc',
    height: '302px',
    letterSpace: '0.93px',
    maxWidth: '717px',
  }],
  tablet: [{
    left: false,
    backgroundColor: '#FFFFFF',
    textColor: '#000000',
    order: '01',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'CONNECTION',
    info: 'Connect with coaches directly, you can ping coaches to view profile.',
    height: '191px',
    letterSpace: '0',
    maxWidth: '457px',
  }, {
    left: false,
    backgroundColor: '#F5F4F9',
    textColor: '#000000',
    order: '02',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'COLLABORATION',
    info: 'Work with other student athletes to increase visability. When you share and like other players videos it will increase your visability as a player. This is the team work aspect to Surface 1.',
    height: '235px',
    letterSpace: '0.837px',
    maxWidth: '446.2px',
  }, {
    left: false,
    backgroundColor: '#5E3DB3',
    textColor: '#FFFFFF',
    order: '03',
    bulletColor: '#000000',
    bulletLineColor: '#FFFFFF',
    title: 'GROWTH',
    info: 'Resources and tools for you to get better as a student Athelte. Access to training classes, tutor sessions, etc',
    height: '207px',
    letterSpace: '0.837px',
    maxWidth: '446.2px',
  }],
  mobile: [{
    left: false,
    backgroundColor: '#FFFFFF',
    textColor: '#000000',
    order: '01',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'CONNECTION',
    info: 'Connect with coaches directly, you can ping coaches to view profile.',
    height: '284px',
    letterSpace: '0',
    maxWidth: '302px',
  }, {
    left: false,
    backgroundColor: '#F5F4F9',
    textColor: '#000000',
    order: '02',
    bulletColor: '#000000',
    bulletLineColor: '#603EBE',
    title: 'COLLABORATION',
    info: 'Work with other student athletes to increase visability. When you share and like other players videos it will increase your visability as a player. This is the team work aspect to Surface 1.',
    height: '284px',
    letterSpace: '0.837px',
    maxWidth: '302px',
  }, {
    left: false,
    backgroundColor: '#5E3DB3',
    textColor: '#FFFFFF',
    order: '03',
    bulletColor: '#000000',
    bulletLineColor: '#FFFFFF',
    title: 'GROWTH',
    info: 'Resources and tools for you to get better as a student Athelte. Access to training classes, tutor sessions, etc',
    height: '284px',
    letterSpace: '0.837px',
    maxWidth: '302px',
  }],
}

export default FootballConfig